trigger: none

schedules:
- cron: "0 21 * * 0"
  displayName: Weekly Sunday cleanup
  branches:
    include:
    - master
  always: true

variables:
- name: poolname
  value: sitecore-docker-images
- name: resourcegroup
  value: valtechazurepipelines-rg

stages:
- stage: cleanup_windows
  dependsOn: []
  jobs:
  - job: prune
    timeoutInMinutes: 480
    pool:
      name: $(poolname)
      demands:
      - Agent.OS -equals Windows_NT
      - Agent.OSVersion -equals 10.0.18363
      - docker
    steps:
    - checkout: none

    - pwsh: |
        Get-Service docker
        Start-Service docker
        Get-Service docker
      displayName: Prepare

    - pwsh: docker system prune --volumes --force
      displayName: Prune

- stage: cleanup_linux
  dependsOn: []
  jobs:
  - job: start_vms
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: none

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(resourcegroup)
        scriptType: pscore
        scriptLocation: inlineScript
        powerShellErrorActionPreference: stop
        inlineScript: az vm start --ids (az resource list --tag pool=$(poolname) --tag platform=linux --query "[?type=='Microsoft.Compute/virtualMachines'].id" -o tsv)
      displayName: 'Start agent vms'

  - job: prune
    dependsOn:
      - start_vms
    timeoutInMinutes: 480
    pool:
      name: $(poolname)
      demands:
        - Agent.OS -equals Linux
        - docker
    steps:
      - checkout: none

      - powershell: docker system prune --volumes --force
        displayName: Prune

  - job: stop_vms
    dependsOn:
      - prune
    pool:
      vmImage: ubuntu-18.04
    steps:
      - checkout: none

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(resourcegroup)
          scriptType: pscore
          scriptLocation: inlineScript
          powerShellErrorActionPreference: stop
          inlineScript: az vm deallocate --no-wait --ids (az resource list --tag pool=$(poolname) --tag platform=linux --query "[?type=='Microsoft.Compute/virtualMachines'].id" -o tsv)
        displayName: 'Deallocate agent vms'