trigger: none

schedules:
- cron: "0 21 * * 0"
  displayName: Weekly Sunday cleanup
  branches:
    include:
    - master
  always: true

stages:
  - stage: cleanup
    dependsOn: []
    jobs:
      - job: prune_windows
        timeoutInMinutes: 480
        pool:
          name: windows-1909
        steps:
          - checkout: none
          - script: docker system prune --volumes --force
            displayName: Prune
      - job: prune_linux
        timeoutInMinutes: 480
        pool:
          name: linux
        steps:
          - checkout: none
          - powershell: |
              docker system prune --volumes --force
            displayName: Prune
