trigger: none

variables:
- name: resource_group_service_connection
  value: valtechshared-rg
- name: registry_name
  value: valtech

schedules:
- cron: "0 22 * * 3"
  displayName: Weekly Wednesday maintenence
  branches:
    include:
    - master
  always: true

stages:
- stage: maintenence
  displayName: ACR maintenence
  jobs:
  - job: cleanup
    displayName: Cleanup
    timeoutInMinutes: 1440
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: none

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(resource_group_service_connection)
        scriptType: pscore
        scriptLocation: inlineScript
        powerShellErrorActionPreference: stop
        inlineScript: |
          az acr show-usage --resource-group $(resource_group_service_connection) --name $(registry_name) --output table
      displayName: Show current usage

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(resource_group_service_connection)
        scriptType: pscore
        scriptLocation: inlineScript
        powerShellErrorActionPreference: stop
        inlineScript: |
          $repositories = (az acr repository list --name $(registry_name) -o tsv)

          foreach ($repository in $repositories)
          {
              Write-Host "Cleaning untagged images in '$repository'..."

              az acr repository show-manifests --name $(registry_name) --repository $repository --query "[?tags[0]==null].digest" -o tsv | ForEach-Object {
                  az acr repository delete --name$(registry_name) --image $repository@$_ --yes
              }
          }
      displayName: Delete untagged images

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(resource_group_service_connection)
        scriptType: pscore
        scriptLocation: inlineScript
        powerShellErrorActionPreference: stop
        inlineScript: |
          az acr show-usage --resource-group $(resource_group_service_connection) --name $(registry_name) --output table
      displayName: Show current usage