# The following variables need to be set in Azure Devops:

# Assets drive
# - (optional) assets.azure.fileshare.password
# - (optional) assets.shared.folder.server
# - assets.useDrive

# Image build options
# - build.includeExperimentalImages
# - build.includeJss
# - build.includeSh
# - build.includeSpe
# - build.includeSxa
# - build.includeShortTags
# - build.linuxImages
# - build.pruneImages
# - build.sitecoreTopology
# - build.sitecoreVersion
# - build.skipExistingImages

# Container registry
# - container.registry.fullname
# - container.registry.password
# - container.registry.username

# Linux
# - (optional) linux.install.source.path

# Sitecore credentials
# - sitecore.password
# - sitecore.username

# Windows:
# - windows.install.source.path

trigger:
  batch: true
  branches:
    include:
    - master

stages:
  - stage: Build_Images
    jobs:
      - job: Build_Images
        strategy:
          matrix:
            windows20H2:
              poolName: 'docker-20H2-agents'
              osVersion: '20H2'
            windows2004:
              poolName: 'docker-2004-agents'
              osVersion: '2004'
            ltsc2019:
              poolName: 'docker-ltsc2019-agents'
              osVersion: 'ltsc2019'
            linux:
              poolName: 'docker-20H2-agents'
              osVersion: 'linux'


        timeoutInMinutes: 720
        displayName: "Build Images"
        pool:
          name: $(poolName)
        steps:
          - checkout: self
            clean: true
          - powershell: |
              Test-NetConnection -ComputerName "$(assets.shared.folder.server)" -Port 445
              Invoke-Expression -Command "cmdkey /add:$(assets.shared.folder.server) /user:Azure\dockerassets /pass:$(assets.azure.fileshare.password)"
              New-PSDrive -Name Z -PSProvider FileSystem -Root "\\$(assets.shared.folder.server)\docker-assets" -Persist -ErrorAction SilentlyContinue
            condition: eq(variables['assets.useDrive'], 'true')
            displayName: "Connect Asset Drive (optional)"

          - powershell: |
              $sitecoreRegistry = "$(sitecore.container.registry)"
              $sitecoreVersion = "$(build.sitecoreVersion)"

              if ("$(Build.SourceBranch)" -match "upgrade/(?<version>\d+\.\d+\.\d+)") {
                  $sitecoreVersion = $matches.version
                  $sitecoreRegistry = "$(sitecore.internal.container.registry)"
              }
              az login -u "$(sitecore.container.registry.username)" -p "$(sitecore.container.registry.password)" -t "$(sitecore.container.registry.tenant)"
              if ("sitecoreRegistry" -ne "scr.sitecore.com"){
                az acr login -n "$sitecoreRegistry"
              }
                az acr login -n "$(container.registry.fullname)"

              $topology = "$(build.sitecoreTopology)" -split ","
              $buildProps = @{
                InstallSourcePath = "$(windows.install.source.path)"
                Registry = "$(container.registry.fullname)"
                RegistryUserName = "$(container.registry.username)"
                RegistryPassword = "$(container.registry.password)"
                SitecoreRegistry = "$sitecoreRegistry"
                SitecoreVersion = "$sitecoreVersion"
                Topology = $topology
                OSVersion = "$(osVersion)"
                IncludeSpe = [System.Convert]::ToBoolean($(build.includeSpe))
                IncludeSxa = [System.Convert]::ToBoolean($(build.includeSxa))
                IncludeJss = [System.Convert]::ToBoolean($(build.includeJss))
                IncludeSh = [System.Convert]::ToBoolean($(build.includeSh))
                IncludeExperimental = [System.Convert]::ToBoolean($(build.includeExperimentalImages))
                SkipExistingImage = [System.Convert]::ToBoolean($(build.skipExistingImages))
                IncludeShortTags = [System.Convert]::ToBoolean($(build.includeShortTags))
              }

              .\Build.ps1 @buildProps
            displayName: "Build Images"
          - powershell: |
                docker image prune --force
            condition: and(succeeded(), eq(variables['build.pruneImages'], 'true'))
            displayName: 'Prune images (optional)'
  - stage: Trigger_Harbor_Push
    dependsOn:
    - Build_Images
    condition: and(succeeded('Build_Images'),eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Harbor_Push
        displayName: 'Harbor Push'
        steps:
        - task: TriggerBuild@3
          displayName: "Trigger Community Modules"
          inputs:
            definitionIsInCurrentTeamProject: true
            buildDefinition: '103'
            queueBuildForUserThatTriggeredBuild: true
            ignoreSslCertificateErrors: false
            useSameSourceVersion: false
            useCustomSourceVersion: false
            useSameBranch: false
            branchToUse: 'main'
            waitForQueuedBuildsToFinish: false
            storeInEnvironmentVariable: false
            buildParameters: 'namespace: community, groupName: communityModules, tag:""'
            authenticationMethod: 'Personal Access Token'
            password: '$(System.AccessToken)'
            enableBuildInQueueCondition: false
            dependentOnSuccessfulBuildCondition: false
            dependentOnFailedBuildCondition: false
            checkbuildsoncurrentbranch: false
            failTaskIfConditionsAreNotFulfilled: false

        - task: TriggerBuild@3
          displayName: "Trigger Community Images"
          inputs:
            definitionIsInCurrentTeamProject: true
            buildDefinition: '103'
            queueBuildForUserThatTriggeredBuild: true
            ignoreSslCertificateErrors: false
            useSameSourceVersion: false
            useCustomSourceVersion: false
            useSameBranch: false
            branchToUse: 'main'
            waitForQueuedBuildsToFinish: false
            storeInEnvironmentVariable: false
            buildParameters: 'namespace: community, groupName: community, tag:""'
            authenticationMethod: 'Personal Access Token'
            password: '$(System.AccessToken)'
            enableBuildInQueueCondition: false
            dependentOnSuccessfulBuildCondition: false
            dependentOnFailedBuildCondition: false
            checkbuildsoncurrentbranch: false
            failTaskIfConditionsAreNotFulfilled: false