# The following variables need to be set in Azure Devops:

# Azure
# - azure.subscription
# - azure.agentPoolName
# - azure.vm.resourceGroupName
# - (optional) azure.vm.linux.name
# - azure.vm.windows.name
#
# Image build options
# - build.triggerAdditionalBuild - specify a build ID for triggering an additional build after successful completion
# - build.tags
# - build.pushMode
# - build.pruneImages
# - build.sitecoreVersion
# - build.sitecoreTopology
# - build.sitecoreWindowsVersion
# - build.includeSpe
# - build.includeSxa
# - build.includeJss
# - build.includeSh
# - build.skipExistingImages
# - build.includeExperimentalImages

# Sitecore credentials
# - sitecore.username
# - sitecore.password
#
# Container registry
# - container.registry.password
# - container.registry.username
# - container.registry.fullname
#
# Windows:
# - windows.install.source.path
#
# Assets drive
# - assets.useDrive
# - (optional) assets.azure.fileshare.password
# - (optional) assets.shared.folder.server
#
# Linux
# - linux.buildImages
# - (optional) linux.install.source.path

trigger:
  batch: true
  branches:
    include:
    - master
schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
      - master
    always: true

stages:
  - stage: Build_Windows_Images
    jobs:
      - job: Build_Windows_Images
        strategy:
          matrix:
            windows2004:
              poolName: 'docker-2004-agents'
              osVersion: '2004'
            ltsc2019:
              poolName: 'docker-ltsc2019-agents'
              osVersion: 'ltsc2019'
              
        timeoutInMinutes: 720
        displayName: "Build Windows Images"
        pool:
          name: $(poolName)
        steps:
          - powershell: |
              Test-NetConnection -ComputerName "$(assets.shared.folder.server)" -Port 445
              Invoke-Expression -Command "cmdkey /add:$(assets.shared.folder.server) /user:Azure\dockerassets /pass:$(assets.azure.fileshare.password)"
              New-PSDrive -Name Z -PSProvider FileSystem -Root "\\$(assets.shared.folder.server)\docker-assets" -Persist -ErrorAction SilentlyContinue
            condition: eq(variables['assets.useDrive'], 'true')
            displayName: "Connect Asset Drive (optional)"
          - task: Docker@2
            displayName: "Docker registry login"
            inputs:
              containerRegistry: "docker-registry"
              command: login
          - checkout: self
            clean: true
          - powershell: |
              "$(container.registry.password)" | docker login -u "$(container.registry.username)" --password-stdin $(container.registry.fullname)
              $topology = "$(build.sitecoreTopology)" -split ","
              $buildProps = @{
                InstallSourcePath = "$(windows.install.source.path)"
                SitecoreUsername = "$(sitecore.username)"
                SitecorePassword = "$(sitecore.password)"
                Registry = "$(container.registry.fullname)"
                RegistryUserName = "$(container.registry.username)"
                RegistryPassword = "$(container.registry.password)"
                SitecoreVersion = "$(build.sitecoreVersion)"
                Topology = $topology
                OSVersion = "$(build.WindowsOSVersion)"
                IncludeSpe = [System.Convert]::ToBoolean($(build.includeSpe))
                IncludeSxa = [System.Convert]::ToBoolean($(build.includeSxa))
                IncludeJss = [System.Convert]::ToBoolean($(build.includeJss))
                IncludeSh = [System.Convert]::ToBoolean($(build.includeSh))
                IncludeExperimental = [System.Convert]::ToBoolean($(build.includeExperimentalImages))
                SkipExistingImage = [System.Convert]::ToBoolean($(build.skipExistingImages))
              }

              .\Build.ps1 @buildProps
            displayName: "Build Images"
          - powershell: |
                docker image prune --force
            condition: and(succeeded(), eq(variables['build.pruneImages'], 'true'))
            displayName: 'Prune images (optional)'
  - stage: Build_Linux_Images
    dependsOn: []
    jobs:
      - job: Build_Linux_Images
        timeoutInMinutes: 720
        displayName: "Build Linux Images"
        condition: eq(variables['build.linuxImages'], 'true')
        pool:
          name: 'docker-linux-agents'
        steps:
          - task: Bash@3
            displayName: "Connect to asset drive"
            condition: eq(variables['assets.useDrive'], 'true')
            inputs:
                targetType: inline
                script: |
                  if [ -d "$(linux.install.source.path)" ]; then
                  exit 0
                  fi
                  sudo mkdir $(linux.install.source.path)

                  if [ ! -d "/etc/smbcredentials" ]; then
                  sudo mkdir /etc/smbcredentials
                  fi
                  if [ ! -f "/etc/smbcredentials/dockerassets.cred" ]; then
                      sudo bash -c 'echo "username=dockerassets" >> /etc/smbcredentials/dockerassets.cred'
                      sudo bash -c 'echo "password=$(assets.azure.fileshare.password)" >> /etc/smbcredentials/dockerassets.cred'
                  fi
                  sudo chmod 600 /etc/smbcredentials/dockerassets.cred

                  sudo bash -c 'echo "//$(assets.shared.folder.server)/docker-assets $(linux.install.source.path) cifs nofail,vers=3.0,credentials=/etc/smbcredentials/dockerassets.cred,dir_mode=0777,file_mode=0777,serverino" >> /etc/fstab'
                  sudo mount -t cifs //$(assets.shared.folder.server)/docker-assets $(linux.install.source.path) -o vers=3.0,credentials=/etc/smbcredentials/dockerassets.cred,dir_mode=0777,file_mode=0777,serverino
          - task: Docker@2
            enabled: true
            displayName: "Docker registry login"
            inputs:
                containerRegistry: "docker-registry"
                command: login
          - checkout: self
            clean: true
          - powershell: |
                sudo chmod 777 /mnt/dockerassets -R
                "$(container.registry.password)" | docker login -u "$(container.registry.username)" --password-stdin $(container.registry.fullname)
                $topology = "$(build.sitecoreTopology)" -split ","
                $buildProps = @{
                  InstallSourcePath = "$(linux.install.source.path)"
                  SitecoreUsername = "$(sitecore.username)"
                  SitecorePassword = "$(sitecore.password)"
                  Registry = "$(container.registry.fullname)"
                  RegistryUserName = "$(container.registry.username)"
                  RegistryPassword = "$(container.registry.password)"
                  SitecoreVersion = "$(build.sitecoreVersion)"
                  Topology = $topology
                  OSVersion = "linux"
                  IncludeSpe = [System.Convert]::ToBoolean($(build.includeSpe))
                  IncludeSxa = [System.Convert]::ToBoolean($(build.includeSxa))
                  IncludeJss = [System.Convert]::ToBoolean($(build.includeJss))
                  IncludeSh = [System.Convert]::ToBoolean($(build.includeSh))
                  IncludeExperimental = [System.Convert]::ToBoolean($(build.includeExperimentalImages))
                  SkipExistingImage = [System.Convert]::ToBoolean($(build.skipExistingImages))
                }

                .\Build.ps1 @buildProps
            displayName: "Build Linux Images"
          - powershell: |
                docker image prune --force
            condition: and(succeeded(), eq(variables['build.pruneImages'], 'true'))
  - stage: Trigger_Harbor_Push
    dependsOn:
    - Build_Windows_Images
    - Build_Linux_Images
    condition: and(succeeded('Build_Windows_Images'), succeeded('Build_Linux_Images'),eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Harbor_Push
        displayName: 'Harbor Push'
        steps:
        - task: TriggerBuild@3
          displayName: "Trigger Community XP"
          inputs:
            definitionIsInCurrentTeamProject: true
            buildDefinition: '103'
            queueBuildForUserThatTriggeredBuild: true
            ignoreSslCertificateErrors: false
            useSameSourceVersion: false
            useCustomSourceVersion: false
            useSameBranch: false
            branchToUse: 'master'
            waitForQueuedBuildsToFinish: false
            storeInEnvironmentVariable: false
            buildParameters: 'namespace: community, groupName: xp, tag:""'
            authenticationMethod: 'Personal Access Token'
            password: '$(System.AccessToken)'
            enableBuildInQueueCondition: false
            dependentOnSuccessfulBuildCondition: false
            dependentOnFailedBuildCondition: false
            checkbuildsoncurrentbranch: false
            failTaskIfConditionsAreNotFulfilled: false

        - task: TriggerBuild@3
          displayName: "Trigger Community XM"
          inputs:
            definitionIsInCurrentTeamProject: true
            buildDefinition: '103'
            queueBuildForUserThatTriggeredBuild: true
            ignoreSslCertificateErrors: false
            useSameSourceVersion: false
            useCustomSourceVersion: false
            useSameBranch: false
            branchToUse: 'master'
            waitForQueuedBuildsToFinish: false
            storeInEnvironmentVariable: false
            buildParameters: 'namespace: community, groupName: xm, tag:""'
            authenticationMethod: 'Personal Access Token'
            password: '$(System.AccessToken)'
            enableBuildInQueueCondition: false
            dependentOnSuccessfulBuildCondition: false
            dependentOnFailedBuildCondition: false
            checkbuildsoncurrentbranch: false
            failTaskIfConditionsAreNotFulfilled: false